"""Create Damain table

Revision ID: 326ad90a1c1e
Revises:
Create Date: 2025-10-22 11:23:50.454794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "326ad90a1c1e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("domain_name", sa.String(length=150), nullable=False),
        sa.Column("ip_address", sa.String(length=150), nullable=True),
        sa.Column(
            "block_list",
            sa.Enum("WEBSITE", "ADVERTISING", name="blocklistenum"),
            nullable=False,
        ),
        sa.Column(
            "created_date",
            sa.Integer(),
            server_default=sa.text(
                "CAST(to_char(now(),'YYYYMMDD') AS INTEGER)"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_time",
            sa.Integer(),
            server_default=sa.text(
                "CAST(to_char(now(),'HH24MISS') AS INTEGER)"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domains_domain_name"), "domains", ["domain_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_domains_domain_name"), table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
