"""Create domain_logs table

Revision ID: aece4fcc2d4e
Revises: 326ad90a1c1e
Create Date: 2025-10-22 11:46:54.292008

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aece4fcc2d4e"
down_revision: Union[str, Sequence[str], None] = "326ad90a1c1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_logs",
        sa.Column(
            "parse_domain_quantity",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "new_domain_quantity",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "remove_domain_quantity",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "log_status",
            sa.Enum("OK", "FAILED", name="logstatusenum"),
            nullable=False,
        ),
        sa.Column(
            "created_date",
            sa.Integer(),
            server_default=sa.text(
                "CAST(to_char(now(),'YYYYMMDD') AS INTEGER)"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_time",
            sa.Integer(),
            server_default=sa.text(
                "CAST(to_char(now(),'HH24MISS') AS INTEGER)"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("domain_logs")
    # ### end Alembic commands ###
