"""Add unique constraint on (domain_name, block_list)

Revision ID: 603c9f6834b5
Revises: aece4fcc2d4e
Create Date: 2025-10-23 16:47:34.349285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "603c9f6834b5"
down_revision: Union[str, Sequence[str], None] = "aece4fcc2d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_domains_domain_name"), table_name="domains")
    op.create_unique_constraint(
        "uix_domain_blocklist", "domains", ["domain_name", "block_list"]
    )
    op.create_unique_constraint(None, "domains", ["domain_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "domains", type_="unique")
    op.drop_constraint("uix_domain_blocklist", "domains", type_="unique")
    op.create_index(
        op.f("ix_domains_domain_name"), "domains", ["domain_name"], unique=True
    )
    # ### end Alembic commands ###
