"""Add column block_list to DomainLog table

Revision ID: 0d777eac4398
Revises: 603c9f6834b5
Create Date: 2025-10-23 17:44:52.954011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d777eac4398"
down_revision: Union[str, Sequence[str], None] = "603c9f6834b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domain_logs",
        sa.Column(
            "block_list",
            sa.Enum("WEBSITE", "ADVERTISING", name="blocklistenum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domain_logs", "block_list")
    # ### end Alembic commands ###
